swipe:
        3:
                up:
                        command: '/home/egnelson/local/bin/winmgr up'
                down:
                        command: '/home/egnelson/local/bin/winmgr down'
                left:
                        command: '/home/egnelson/local/bin/winmgr switch right'
                right:
                        command: '/home/egnelson/local/bin/winmgr switch left'
        4:
                up:
                        command: '/home/egnelson/local/bin/winmgr up'
                down:
                        command: '/usr/bin/dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:1'
                left:
                        command: '/home/egnelson/local/bin/winmgr move left'
                right:
                        command: '/home/egnelson/local/bin/winmgr move right'
pinch:
        3:
                in:
                        command: '/home/egnelson/local/bin/winmgr fullscreen'
